name = "BarSpringModels"
uuid = "a0e4d741-e497-4d5d-9129-eacc56e0f522"
authors = ["Damir Akchurin <AkchurinDA@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
